all: # Grupo contendo todos os subgrupos e servidores do projeto.
    children: # Modulo que permite a criação de subgrupos.
        backend: # Nome do primeiro grupo do nosso inventário
            hosts: #  Modulo que permite declarar os servidores em um grupo.
                db-machine: # Nome dado ao servidor de banco de dados.
                    ansible_host: XXX.XXX.XXX.XXX # Endereço de ip do servidor remoto que será fornecido pela integração com terraform.
                    ansible_user: ubuntu # Usuario local do servidor remoto.
                    ansible_ssh_private_key_file: ./inventory/webbudget.pem # Chave privada para acesso SSH ao servidor remoto. 
        frontend:  # Nome dado aos servidores da aplicação web.
            hosts: #  Modulo que permite declarar os servidores em um grupo.
                web-machine-1: # Nome dado ao servidor primeiro servidor da aplicação web.
                    ansible_host: XXX.XXX.XXX.XXX # Endereço de ip do servidor remoto que será fornecido pela integração com terraform.
                    ansible_user: ubuntu # Usuario local do servidor remoto.
                    ansible_ssh_private_key_file: ./inventory/webbudget.pem # Chave privada para acesso SSH ao servidor remoto. 
                
                web-machine-2: # Nome dado ao servidor segundo servidor da aplicação web.
                    ansible_host: XXX.XXX.XXX.XXX # Endereço de ip do servidor remoto que será fornecido pela integração com terraform.
                    ansible_user: ubuntu # Usuario local do servidor remoto.
                    ansible_ssh_private_key_file: ./inventory/webbudget.pem # Chave privada para acesso SSH ao servidor remoto. 